{ pkgs, ... }:

{
  # Git
  programs.git = {
    enable = true;
    userName = "endafk";
    userEmail = "254jaymz@gmail.com";
    delta = {
      enable = true;                     # pretty diffs with syntax highlighting
      options = {
        navigate = true;
        side-by-side = true;
        line-numbers = true;
      };
    };
    extraConfig = {
      init.defaultBranch = "main";
      pull.rebase = true;
      merge.conflictstyle = "zdiff3";    # clearer conflict markers
      diff.algorithm = "histogram";      # better diff output
      rerere.enabled = true;             # remember conflict resolutions
    };
  };

  # Neovim
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
  };

  # Bash
  programs.bash.enable = true;

  # Fish
  programs.fish = {
    enable = true;
    interactiveShellInit = ''
      # Silence
      set -g fish_greeting

      # History search with arrows
      bind \e\[A history-search-backward
      bind \e\[B history-search-forward

      # Color tweaks
      set -g fish_color_command green
      set -g fish_color_param normal
      set -g fish_color_error red --bold
      set -g fish_color_comment brblack
      set -g fish_color_autosuggestion brblack
      set -g fish_color_valid_path --underline

      # Fastfetch on first interactive shell (skip nested/tmux/vscode)
      if status is-interactive; and not set -q FASTFETCH_SHOWN
        set -gx FASTFETCH_SHOWN 1
        fastfetch
      end
    '';
  };

  # Starship prompt (config generated by gen-starship.py for correct Unicode)
  programs.starship = {
    enable = true;
    enableFishIntegration = true;
    enableBashIntegration = true;
  };
  xdg.configFile."starship.toml".source = ./config/starship.toml;
  xdg.configFile."fastfetch/config.jsonc".source = ./config/fastfetch.jsonc;

  # Tmux
  programs.tmux = {
    enable = true;
    terminal = "tmux-256color";
    mouse = true;
    keyMode = "vi";
    baseIndex = 1;
    escapeTime = 0;
    historyLimit = 50000;
    extraConfig = ''
      # ── Prefix ──
      unbind C-b
      set -g prefix C-a
      bind C-a send-prefix

      # ── Splits ──
      bind | split-window -h -c "#{pane_current_path}"
      bind - split-window -v -c "#{pane_current_path}"
      unbind '"'
      unbind %

      # ── Pane nav (Alt+arrow, no prefix) ──
      bind -n M-Left select-pane -L
      bind -n M-Right select-pane -R
      bind -n M-Up select-pane -U
      bind -n M-Down select-pane -D

      # ── Resize (prefix + Shift+arrow) ──
      bind -r S-Left resize-pane -L 2
      bind -r S-Right resize-pane -R 2
      bind -r S-Up resize-pane -U 2
      bind -r S-Down resize-pane -D 2

      # ── Windows ──
      bind c new-window -c "#{pane_current_path}"
      bind -n M-1 select-window -t 1
      bind -n M-2 select-window -t 2
      bind -n M-3 select-window -t 3
      bind -n M-4 select-window -t 4
      bind -n M-5 select-window -t 5

      # ── Reload ──
      bind r source-file ~/.config/tmux/tmux.conf \; display " Reloaded"

      # ── Visual ──
      set -g status-position top
      set -g status-interval 5
      set -g status-style "fg=#a0a0a0,bg=default"
      set -g status-left "#[bold,fg=blue] #S "
      set -g status-left-length 20
      set -g status-right "#[fg=#707070] #(whoami)@#h #[fg=#606060] %H:%M"
      set -g status-right-length 40

      setw -g window-status-format "#[fg=#606060] #I:#W "
      setw -g window-status-current-format "#[bold,fg=green] #I:#W "

      set -g pane-border-style "fg=#303030"
      set -g pane-active-border-style "fg=#505050"

      set -g message-style "fg=yellow,bg=default"

      # ── True color ──
      set -as terminal-features ",xterm-256color:RGB"
    '';
  };

  # Zoxide (frecency-based cd replacement)
  programs.zoxide = {
    enable = true;
    enableFishIntegration = true;
    enableBashIntegration = true;
    options = [ "--cmd cd" ];
  };

  # Direnv (auto-load .envrc per project)
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  # fzf (fuzzy finder integration with shell)
  programs.fzf = {
    enable = true;
    enableFishIntegration = true;
    enableBashIntegration = true;
    defaultCommand = "rg --files --hidden --glob '!.git'";
    defaultOptions = [ "--height=40%" "--layout=reverse" "--border" ];
  };
}
