format = """\
$directory\
$git_branch\
$git_status\
$kubernetes\
$docker_context\
$python\
$golang\
$nodejs\
$terraform\
$nix_shell\
$cmd_duration\
$line_break\
$character"""

right_format = """\
$status\
$username\
$hostname\
$time"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"

[status]
disabled = false
symbol = " "
format = "[$symbol$status]($style) "
style = "bold red"

[username]
show_always = true
format = "[$user]($style)@"
style_user = "bold yellow"
style_root = "bold red"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold yellow"

[time]
disabled = false
format = " $time"
time_format = "%H:%M"
style = "#606060"

[directory]
truncation_length = 4
truncate_to_repo = true
style = "bold cyan"
read_only = " "

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold purple"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold red"
stashed = " "
ahead = "↑${count}"
behind = "↓${count}"
diverged = "↑${ahead_count}↓${behind_count}"
conflicted = "=${count}"
deleted = "✘${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"

[kubernetes]
disabled = false
symbol = "☸ "
format = "[$symbol$context(/$namespace)]($style) "
style = "bold blue"

[docker_context]
symbol = " "
format = "[$symbol$context]($style) "
style = "blue"
only_with_files = true

[terraform]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold 105"

[python]
symbol = " "
format = "[$symbol$version($virtualenv)]($style) "
style = "bold yellow"

[golang]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold cyan"

[nodejs]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold green"

[nix_shell]
symbol = " "
format = "[$symbol$state]($style) "
style = "bold blue"

[cmd_duration]
min_time = 1_500
format = "[took $duration]($style) "
style = "bold yellow"
